[metadata]
version = "1.0"

[versions]
indra = "3.1.3"

configurate = "4.1.2"
paper = "1.21-R0.1-SNAPSHOT"

[libraries]
configurate-core = { module = "org.spongepowered:configurate-core", version.ref = "configurate" }
configurate-yaml = { module = "org.spongepowered:configurate-yaml", version.ref = "configurate" }
paper = { module = "io.papermc.paper:paper-api", version.ref = "paper" }

build-indra = { module = "net.kyori:indra-common", version.ref = "indra" }
build-indra-spotless = { module = "net.kyori:indra-licenser-spotless", version.ref = "indra" }
